---
- name: config | Update default RabbitMQ Configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: etc/rabbitmq/rabbitmq.conf.j2, dest: /etc/rabbitmq/rabbitmq.conf }
    - { src: etc/rabbitmq/rabbitmq-env.conf.j2, dest: /etc/rabbitmq/rabbitmq-env.conf }
  notify:
    - restart rabbitmq-server

- name: Enable the plugins is installed
  rabbitmq_plugin:
    names: "{{ item }}"
    prefix: /usr/lib/rabbitmq
    state: enabled
    new_only: "{{ rabbitmq_plugins_new_only }}"
  with_items: "{{ rabbitmq_plugins }}"
  notify:
    - restart rabbitmq-server
