---

- include_tasks: hosts.yml
  when:
    - rabbitmq_update_hosts

- include_tasks: debian.yml
  when:
    - ansible_os_family == 'Debian'

- include_tasks: erlang_cookie.yml
  when:
    - rabbitmq_cluster

- include_tasks: tls.yml
  when:
    - rabbitmq_enable_tls

- include_tasks: config.yml

- include_tasks: service.yml

- include_tasks: plugins.yml

- include_tasks: cluster.yml
  when:
    - rabbitmq_cluster

- include_tasks: create_users.yml

- include_tasks: create_policies.yml
